#!/usr/bin/python
# -*- coding: utf-8 -*-
Import('env')

files = [
	'connecthostport.c',
	'igd_desc_parse.c',
	'minisoap.c',
	'minissdpc.c',
	'miniupnpc.c',
	'miniwget.c',
	'minixml.c',
	'upnpcommands.c',
	'upnperrors.c',
	'upnpreplyparse.c']

ret = env.StaticLibrary(target = 'miniupnpc', source = files)

Return('ret')
