#!/usr/bin/env python
# -*- coding: utf-8 -*-
Import('env')
from sys import platform as _platform

env = env.Clone()

files =  ( [
'connecthostport.c',
'igd_desc_parse.c',
'minisoap.c',
'minissdpc.c',
'miniupnpc.c',
'miniwget.c',
'minixml.c',
'portlistingparse.c',
'receivedata.c',
'upnpcommands.c',
'upnpdev.c',
'upnperrors.c',
'upnpreplyparse.c',
])

env.Append(CPPFLAGS = '-Wno-unused-parameter')
env.Append(CPPDEFINES = ['STATICLIB'])

if _platform == "win32":
	env.Append(LIBS = ['wsock32','iphlpapi','ws2_32'])


ret = env.StaticLibrary(target = 'miniupnpc', source = files)
Return('ret')
