sudo: required
dist: trusty

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ntn+5VcHkWiyzkBeKAT/IcXvWv6ueimb0pFNt4+KQNT79tcAliXB+kEAahVMRY4YEF4V8WxlTgFWysCmnPk9PnoJ2xpYmSZdWk+O1rhSBoNwmlXOiskYriP+DVzvx99M8XZTWyMq3DyveO5qrYxr7raRvgottzjxRhuQ4Z2CO9SQSCkTsGYZfqj38WbQns/6+NEHrJ5zyYHETxnXuNgObLEBFZhO+j98VSAD707qjrAnfP5ilsNRPheOwIlz/1IQumanHgZIIhXQ/gB0fccgBtdYo1brAeWPbCQeSSKMTpHfwBMKTQzkhLxhC9R7Hl3x07tpsSeFdTLrse/EjSL4utm65WKOr1nbf1w+d6j4C2OzlYBLG9oSqBLJZ73PhjnULyaCASXVQQxlSoXTeS0e5U7JLnP5H8yiqQCrrHMDWjShJDULmvqfa0tFxQkbPxofcfi73VPS7fVIl5xRH5pz4fEtSFZXM2vi4Vjinse3bPY7se8fKuHVC9gHwrRbLEnsb0Fjgmu2r5YYtC8mYkr2mbYyMfqv4tl/xZ+qV86p2WMpFSPby0eMHe4ChjDGvBIInbNMUitu7011H1dEifSS44fR7qwaddmAaQBrQFpCUIp2Q8Whcr+sv9SZ58oWHZfm+ybkJ60DIL47jThFMThnkQzsOjnocQkqfUy0YCfNC3A="


before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y 
  - sudo add-apt-repository ppa:0k53d-karl-f830m/openssl -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-4.8 -y
  - sudo apt-get install openssl -y
  - sudo apt-get install -qq -y scons libbz2-dev zlib1g-dev libgtk-3-dev libssl-dev libcanberra-dev libnotify-dev libgeoip-dev libtar-dev libxss-dev bzr g++ gcc

install: true
script: scons

addons:
  coverity_scan:
    project:
      name: "bmdc-team/bmdc-client"
      description: "Build submitted via Travis CI"
    notification_email: freedcpp@seznam.cz
    build_command_prepend: "scons"
    build_command:   "scons"
    branch_pattern: coverity_scan
