name: bmdc
version: 1.0.25
summary: BMDC client
description: |
  BMDC , the DC++ client for linux.
icon: icons/hicolor/22x22/apps/bmdc.png

apps:
  bmdc:
    command: ./bin/bmdc

parts:
    bmdc:
        plugin: scons
        source: lp:bmdc++
