#!/usr/bin/env python
# -*- coding: utf-8 -*-
Import('env')
from sys import platform as _platform
#_platform = 'win32'

env = env.Clone()
files = env.Glob('*.c')
env.Append(CPPDEFINES = ['STATICLIB'])


if _platform == "win32":
	env.Append(LIBS = ['wsock32','iphlpapi','ws2_32'])
	#env.Append(LINKFLAGS= ['-lwsock32','-lws2_32'])
	#env.Append(LINKFLAGS='-lwsock32')		

ret = env.StaticLibrary(target = 'natpmp', source = files)
Return('ret')
