#!/usr/bin/python
# -*- coding: utf-8 -*-
# 
# (C) 2025 BMDC
# This file is part of BMDC.
# BMDC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
#
# BMDC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with Xfce-nameday-plugin. If not, see <https://www.gnu.org/licenses/>.
#

Import('env')

gui_files = env.Glob('*.cpp')
obj_files = []

env.ParseConfig('pkg-config --cflags --libs gtk4')

# Build the gui_files
obj_files = env.Object(gui_files)

Return('obj_files')
