#!/usr/bin/python
# -*- coding: utf-8 -*-

Import('env')

gui_files = env.Glob('*.cpp')
obj_files = []

env.ParseConfig('pkg-config --cflags --libs gtk+-3.0')

# Build the gui_files
obj_files = env.Object(gui_files)

Return('obj_files')
