#!/usr/bin/env python
# -*- coding: utf-8 -*-

Import('env')

header_files = env.Glob('*.hh')
gui_files = env.Glob('*.cc')
obj_files = []


env.ParseConfig('pkg-config --cflags --libs gtk4')

env.Append(CPPFLAGS = '-IC:/msys64/ucrt64/include/glib-2.0 -IC:/msys64/ucrt64/lib/glib-2.0/include -IC:/msys64/ucrt64/include')

env.Append(CPPFLAGS = '-mfpmath=sse -msse -msse2 -mms-bitfields -IC:/msys64/ucrt64/include/gtk-4.0 -IC:/msys64/ucrt64//include -IC:/msys64/ucrt64/include/pango-1.0 -IC:/msys64/ucrt64/include/harfbuzz -IC:/msys64/ucrt64/include/pango-1.0 -IC:/msys64/ucrt64/include/fribidi -IC:/msys64/ucrt64/include -IC:/msys64/ucrt64/include/gdk-pixbuf-2.0 -IC:/msys64/ucrt64/include -IC:/msys64/ucrt64/include/cairo -IC:/msys64/ucrt64/include/lzo -IC:/msys64/ucrt64//include -IC:/msys64/ucrt64//include/freetype2 -IC:/msys64/ucrt64/include/libpng16 -IC:/msys64/ucrt64/include/harfbuzz -IC:/msys64/ucrt64/include -IC:/msys64/ucrt64/include/pixman-1 -IC:/msys64/ucrt64/include/graphene-1.0 -IC:/msys64/ucrt64/lib/graphene-1.0/include -IC:/msys64/ucrt64/include -IC:/msys64/ucrt64/include/glib-2.0 -IC:/msys64/ucrt64/lib/glib-2.0/include -IC:/msys64/ucrt64/include')

env.Append(CPPDEFINES='PACKAGE=\'\"%s\"\'' % env['package'])

# Build the gui_files
obj_files = env.Object(gui_files)

pot_file = env.PotBuild(source = gui_files + header_files, target='po/linux.pot', LANGUAGE='C++')

Return('pot_file', 'obj_files')
