#!/usr/bin/env python
# -*- coding: utf-8 -*-

Import('env')

header_files = env.Glob('*.hh')
gui_files = env.Glob('*.cc')
obj_files = []

env.ParseConfig('pkg-config --cflags --libs gtk+-3.0')
env.Append(CPPDEFINES='PACKAGE=\'\"%s\"\'' % env['package'])

# Build the gui_files
obj_files = env.Object(gui_files)

pot_file = env.PotBuild(source = gui_files + header_files, target='po/linux.pot', LANGUAGE='C++')

Return('pot_file', 'obj_files')
